version: '3'

services:
  app:
    image: sanggenie/planus_prod
    container_name: planus_prod
#    build:
#      context: ./
#      dockerfile: ./DockerFile/Dockerfile_prod
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always